version: '3.9'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432

  bot:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; /bot'
    ports:
      - 8000:80
    depends_on:
      - db

